apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: web
    app.kubernetes.io/instance: ecom-app
  name: database
  namespace: default
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-rootpass
                  name: mysql-secret
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  key: mysql-username
                  name: mysql-secret
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: mysql-secret
          image: 'jorgescarenzi/ecom-mysql:31'
          name: ecom-mysql
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              cpu: 500m
              memory: 1024Mi
            requests:
              cpu: 200m
              memory: 512Mi
          volumeMounts:
            - mountPath: /var/lib/mysql/
              name: dbdata
            - mountPath: /var/log/
              name: logs
      volumes:
        - name: logs
          persistentVolumeClaim:
            claimName: mysql-pv-claim
