apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: web
spec:
  selector:
    matchLabels:
      app: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: jorgescarenzi/ecom-mysql:31
        name: ecom-mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-rootpass
        - name: MYSQL_USER 
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-username
        - name: MYSQL_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1024Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          mountPath: /var/lib/mysql/
        - name: logs
          mountPath: /var/log/  
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: mysql-pv-claim
